#!/usr/bin/env bash

# --- Arch Linux Automated Proxmox VM Setup (v2.3) ---
# One-shot script. Uses DHCP to "just work" on any network.
# Downloads, builds, and cleans up.
# Sets default password "password". Change it.
# ---

set -e
trap 'error_handler $LINENO "$BASH_COMMAND"' ERR

# --- Configuration Variables ---
VMID=201
VM_NAME="archdev"
CPU_CORES=8
RAM_MB=12288
DISK_SIZE=150G
STORAGE="local-zfs"
BRIDGE="vmbr0"
AUTOSTART="yes"
DEV_PASSWORD="password"

TEMPLATE_DIR="/opt/qcow2/arch_linux"
TEMPLATE_FILE="$TEMPLATE_DIR/Arch-Linux-x86_64-cloudimg.qcow2"
TEMPLATE_URL="https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2"
USER_DATA_FILE="$TEMPLATE_DIR/arch-dev-userdata.yaml"

# --- Helper Functions ---
function error_handler() {
    echo "Error on line $1: $2"
    exit 1
}
function log() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') $1"
}

# --- Phase 1: Artifact Acquisition ---
log "Checking for Arch Linux cloud image..."
if [ ! -f "$TEMPLATE_FILE" ]; then
    log "Image not found. Downloading to $TEMPLATE_FILE..."
    mkdir -p $TEMPLATE_DIR
    wget -O $TEMPLATE_FILE $TEMPLATE_URL
    log "Download complete."
else
    log "Cloud image already exists. Skipping download."
fi

# --- Phase 2: Create Cloud-Init Config from Heredoc ---
log "Generating Cloud-Init config at $USER_DATA_FILE..."
cat > $USER_DATA_FILE << EOF
#cloud-config
# vim: syntax=yaml
# THIS FILE IS AUTO-GENERATED BY create_arch_vm.sh

users:
  - name: devuser
    password: $DEV_PASSWORD
    chpasswd: { expire: False }
    ssh_pwauthentication: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [wheel, docker]
    shell: /bin/bash

# --- NO STATIC IP. WE ARE USING DHCP. ---
# NetworkManager will handle this by default.

runcmd:
  - 'exec > /var/log/archvm-setup.log 2>&1'
  - 'set -x'
  - 'echo "--- $(date) --- Starting Cloud-Init Setup ---"'
  # We will rely on NetworkManager to get an IP.
  - 'pacman -Syu --noconfirm'
  # Note: Removed systemd-networkd to avoid conflict with NetworkManager
  - 'pacman -S --noconfirm base-devel git sudo networkmanager xorg-server xorg-xinit hyprland alacritty kitty neovim'
  - 'systemctl enable NetworkManager'
  - 'pacman -S --noconfirm git nodejs npm python python-pip go docker docker-compose'
  - 'systemctl enable docker'
  - 'systemctl start docker'
  - 'pacman -S --noconfirm firefox chromium thunderbird onlyoffice-bin notepadqq'
  - 'git clone https://github.com/charmbracelet/crush.git /opt/crush'
  - 'cd /opt/crush'
  - 'make install'
  - 'pacman -S --noconfirm samba'
  - 'systemctl enable smb nmb'
  - 'mkdir -p /etc/systemd/system/getty@tty1.service.d'
  - |
    cat > /etc/systemd/system/getty@tty1.service.d/override.conf << EOL
    [Service]
    ExecStart=
    ExecStart=-/sbin/agetty --autologin devuser --noclear %I \$TERM
    EOL
  - 'systemctl daemon-reexec'
  - 'mkdir -p /home/devuser/.config/hypr'
  - "echo '# Start Hyprland automatically on login' >> /home/devuser/.xinitrc"
  - "echo 'exec Hyprland' >> /home/devuser/.xinitrc"
  - 'mkdir -p /home/devuser/Desktop'
  - |
    cat > /home/devuser/Desktop/FirstBootLog.desktop << 'DESKTOP'
    [Desktop Entry]
    Name=First Boot Log
    Comment=Open the Arch VM first-boot setup log
    Exec=alacritty -e less /var/log/archvm-setup.log
    Icon=utilities-terminal
    Terminal=false
    Type=Application
    Categories=Utility;
    DESKTOP
  - 'chown -R devuser:devuser /home/devuser'
  - 'chmod +x /home/devuser/Desktop/FirstBootLog.desktop'
  # Wait for NetworkManager to be fully up before declaring success
  - 'systemctl start NetworkManager'
  - 'echo "--- $(date) --- Cloud-Init Setup Complete ---"'
EOF
log "Cloud-Init config generated."

# --- Phase 3: VM Creation ---
log "Destroying existing VM $VMID (if any) for a clean build..."
qm destroy $VMID --purge || true

log "Creating VM $VMID ($VM_NAME)..."
qm create $VMID -name $VM_NAME -memory $RAM_MB -cores $CPU_CORES \
    -net0 virtio,bridge=$BRIDGE -ostype l26 -onboot 1 -scsihw virtio-scsi-pci \
    -description "Arch Dev VM - provisioned by create_arch_vm.sh"

log "Importing cloud image as disk..."
qm importdisk $VMID $TEMPLATE_FILE $STORAGE
qm set $VMID -virtio0 $STORAGE:vm-$VMID-disk-0,cache=none,discard=on,iothread=1
qm set $VMID -boot order=virtio0

log "Creating Cloud-Init drive..."
pvesm alloc $STORAGE $VMID vm-$VMID-cloudinit 4M
qm set $VMID -ide2 $STORAGE:vm-$VMID-cloudinit,media=cdrom

log "Configuring Cloud-Init parameters..."
qm set $VMID --ciuser devuser
qm set $VMID --cipassword $DEV_PASSWORD
# --- NO --ipconfig0. Let Cloud-Init use DHCP. ---
qm set $VMID --cicustom "user=local:$USER_DATA_FILE"

log "Resizing disk to $DISK_SIZE..."
qm resize $VMID virtio0 $DISK_SIZE

# --- Phase 4: Immediate Cleanup ---
log "Cleaning up source image: $TEMPLATE_FILE"
rm $TEMPLATE_FILE
log "Cleanup complete."

# --- Phase 5: Start VM ---
if [ "$AUTOSTART" == "yes" ]; then
    qm start $VMID
    log "VM $VMID started. Cloud-Init is now provisioning."
fi

log "--- VM Setup Initiated ---"
log "--- HOW TO FIND YOUR IP ---"
log "1. Go to your Proxmox web UI."
log "2. Click on the VM ($VMID, $VM_NAME) in the left-hand tree."
log "3. Go to the 'Summary' tab."
log "4. The IP address will appear under 'Guest IP' (may take 1-2 mins)."
log "---"
log "SSH User: devuser"
log "SSH Pass: $DEV_PASSWORD (⚠️ INSECURE - CHANGE THIS)"
log "---"
log "THE FIRST THING YOU DO: Log in and run 'passwd' to change your password."